name: Build and Test

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image and run tests
        run: docker build -f ServerAnalysisAPI/Dockerfile -t ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest ./ServerAnalysisAPI

      - name: Remove existing container
        run: docker rm serverAnalysisContainer || true

      - name: Push Docker image to GitHub Packages
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest