name: CI/CD

on:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image and run tests
        run: docker build -f ServerAnalysisAPI/Dockerfile -t ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest ./ServerAnalysisAPI

      - name: Remove existing container
        run: docker rm serverAnalysisContainer || true

      - name: Push Docker image to GitHub Packages
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ secrets.USERNAME }} --password-stdin
          docker push ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest

  deploy:
    needs: build_test
    runs-on: ubuntu-latest

    steps:

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Set WEBSITES_PORT setting
        run: |
          az webapp config appsettings set --resource-group thesis --name server-analysis --settings WEBSITES_PORT=8080

      - name: Deploy to Azure
        run: |
          az webapp config container set --name server-analysis --resource-group thesis --docker-custom-image-name ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest --docker-registry-server-url https://ghcr.io --docker-registry-server-user ${{ github.actor }} --docker-registry-server-password ${{ secrets.REGISTRY_TOKEN }}
          az webapp restart --name server-analysis --resource-group thesis

      # - name: Deploy to Render
      #   run: |
      #     curl -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
      #         -H "Content-Type: application/json" \
      #         -X POST \
      #         -d '{
      #               "type": "web",
      #               "name": "serveranalysisapi",
      #               "image": "ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest",
      #               "envVars": [
      #                 {
      #                   "key": "REGISTRY_TOKEN",
      #                   "value": "${{ secrets.REGISTRY_TOKEN }}"
      #                 }
      #               ]
      #             }' \
      #     https://api.render.com/v1/services
