name: CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image and run tests
        run: docker build -f ServerAnalysisAPI/Dockerfile -t ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest ./ServerAnalysisAPI

      - name: Remove existing container
        run: docker rm serverAnalysisContainer || true

      - name: Push Docker image to GitHub Packages
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest

      - name: Deploy to Render
        run: |
          curl https://getcli.rend.run | sh
          render login --token ${{ secrets.RENDER_API_KEY }}
          render deploy --type web --name serveranalysisapi

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure
        run: |
          az webapp config container set --name server-analysis --resource-group thesis --docker-custom-image-name ghcr.io/${{ secrets.USERNAME }}/serveranalysisapi:latest --docker-registry-server-url https://ghcr.io --docker-registry-server-user ${{ github.actor }} --docker-registry-server-password ${{ secrets.REGISTRY_TOKEN }}
          az webapp restart --name server-analysis --resource-group thesis